### ISSUE TITLE
IMU dynamic reconfig checkout

### ISSUE THREAD

**Issue by menson168** [SJSU-AD/FusionAD#101]
![image](https://user-images.githubusercontent.com/15275034/47611868-8e42ee00-da2b-11e8-8cc4-187bd3e94acf.png)

**Comment by menson168** [comment]
Data was collected for finding the residual offset of the imu (zero gain test). Will be implementing that data into the tf node to eliminate the final offset.

**Comment by drofp** [comment]
Do we have a design structure for the master_tf package and know how this will be integrated into that structure? Or is this a temporary quick implementation on a single standalone node?
