### ISSUE TITLE
Cleanup Localization

### ISSUE THREAD

**Issue by drofp** [SJSU-AD/FusionAD#119]
- [ ] Scope the naming convention of [the Odometry node](src/modules/localization/src/wheel_odom/Odometry.cpp) in accordance with [robot_localization's method](http://docs.ros.org/melodic/api/robot_localization/html/state_estimation_nodes.html?highlight=visual)
- [ ] Place all header files in `/include` directory

**Comment by joeyzhu00** [comment]
Done
