### ISSUE TITLE
GPS+IMU Initial Condition Calibration for loam

### ISSUE THREAD

**Issue by joeyzhu00** [SJSU-AD/FusionAD#141]
loam_velodyne requires a set of initial conditions (pose, orientation) for a static transform such that the start point from loam_velodyne is not always at the origin (0,0,0). 

Assumption: Vehicle will not start immediately after launching the launch files and will instead start about a minute afterwards.

Collect data for a minute and then average out the data to determine an initial condition for x-position, y-position, and yaw for a static transform from LiDAR to Front Axle Position. A boolean will be published and each node will be subscribed to that topic to change the position vector in the tf_broadcaster.

**Comment by drofp** [comment]
Is initial implementation of this just going to be with GPS only?  

Also, is this gated by school-frame TF setup?

**Comment by joeyzhu00** [comment]
Initial implementation will be GPS and IMU. School-frame TF setup is something we can decide on. We can also just rotate everything to the GPS frame.

**Comment by joeyzhu00** [comment]
One possible method is to have EKF 1 be reading from IMU, GPS, and Wheel Odom for a minute and then use that estimate as the input to EKF 2 which has IMU, GPS, Wheel Odom, and Lidar.

**Comment by joeyzhu00** [comment]
Will implement using GPS frame, but will eventually use a "School frame" defined by a point-cloud map.

**Comment by joeyzhu00** [comment]
Need to do a message header frame remap in the LaserOdometry.cpp code for the odometry published message from "/camera_init" to odom.

**Comment by joeyzhu00** [comment]
Will also need to add a remapping from an odometry message to chassis_state message.

**Comment by joeyzhu00** [comment]
Add static broadcast transforms to geodesy and IMU remapping nodes as well as loam
