### ISSUE TITLE
Remove yaw publisher from Geodesy

### ISSUE THREAD

**Issue by joeyzhu00** [SJSU-AD/FusionAD#156]
Remove tf_master from geodesy

**Comment by drofp** [comment]
[here](https://github.com/SJSU-AD/FusionAD/blob/develop/src/modules/geodesy/include/geodesy/tf_master.h) and [here](https://github.com/SJSU-AD/FusionAD/blob/develop/src/modules/geodesy/src/tf_master.cpp)
