### ISSUE TITLE
Migrate GPS Driver to ETHZ Piksi

### ISSUE THREAD

**Issue by menson168** [SJSU-AD/FusionAD#168]
[ETHZ Piksi Driver](https://github.com/ethz-asl/ethz_piksi_ros)

**Comment by menson168** [comment]
For @drofp and @joeyzhu00   

- Use topic ```/piksi/navsatfix_best_fix``` in place of ```/gps/fix``` from the old SwiftNav Driver for Lat-Long-Alt input from the GPS  
  
There is also an ENU conversion built into the driver, it's probably worth it to check it out and compare it to our conversion. 

See [Optional ENU Conversion Setup](https://github.com/SJSU-AD/FusionAD/wiki/GPS-Setup---Swiftnav-Piksi-Multi#optional-enu-conversion-setup)

**Comment by menson168** [comment]
See [GPS Setup](https://github.com/SJSU-AD/FusionAD/wiki/GPS-Setup---Swiftnav-Piksi-Multi) for the GPS setup wiki page

**Comment by drofp** [comment]
Hand slipped^

**Comment by menson168** [comment]
Closing issue.
Successfully replicate the migration process on Joey's laptop.

**Comment by drofp** [comment]
**NOTE:** This has not been validated on my laptop yet. We may want to consider keeping this open until we have multiple laptops that can support this, or until Joey's laptop has been backed up on Clonezilla

**Comment by menson168** [comment]
Reopen because @drofp need to try it out on his laptop.

**Comment by menson168** [comment]
@drofp Please close this when you have validated the GPS.

**Comment by drofp** [comment]
Validated on most recent redcar test date
