### ISSUE TITLE
Implement Map Based Localization

### ISSUE THREAD

**Issue by joeyzhu00** [SJSU-AD/FusionAD#183]
Brainstorm methods for implementation
- Create our own package using 2D/3D particle filter
- Use EKF based localization with respect to the point cloud representing "landmarks"
- Or use built-in AMCL package which uses a 2D particle filter

[Brainstormed Framework](https://docs.google.com/document/d/1ApbZo3NWb_CE_2_Ib77nI5UBwdFznktEZQ6ZafoMgVs/edit)

**Comment by menson168** [comment]
I will buy you two beer/boba when this thing works. 

-Menson, 2019

**Comment by menson168** [comment]
Adding @Francisco-Ibarra07 into my reward.
