### ISSUE TITLE
Clean up root dir README

### ISSUE THREAD

**Issue by menson168** [SJSU-AD/FusionAD#200]
I will be rebuilding the initial README at the root directory with more legitimate pictures and guide on how to use our stacks and who's our team.

**Comment by menson168** [comment]
The README page may contain pictures of ours including and not limited to personal headshots, please let me know if you prefer not to have pictures of you included in the README.

**Comment by drofp** [comment]
I think we should include our pictures in the [home page of the wiki](https://github.com/SJSU-AD/FusionAD/wiki) to prevent commits from using excessive space over time.

**Comment by drofp** [comment]
This was a problem early on with perception over summer when there were a lot of pictures saved in each commit, and likely the cause of the current size of the repo

**Comment by menson168** [comment]
Don't think that will be a problem, our pictures will not be stored in the repo but rather referenced from a link in the README
