### ISSUE TITLE
Tune EKF For OSV Platform

### ISSUE THREAD

**Issue by joeyzhu00** [SJSU-AD/FusionAD#205]
Tuning covariance matrix for the EKF with the most recent bags.

**Comment by drofp** [comment]
Which covariance matrix, specifically?

**Comment by joeyzhu00** [comment]
Process noise covariance matrix. 

However, it seems that there may not be much to do as the covariance of the GPS is fixed to a highly accurate value of 0.0049 [m^2]. I had a technically "erroneous" setup for the `robot_localization` package which was dependent on a dynamic covariance from the GPS driver. This was done by using two sources of pose estimates: one from the `geodesy` package and the other from the `wheel_odom` program which causes slight oscillation but good state estimation in the event that GPS signal becomes poor or we lose it completely.

The "technically correct" way to utilize `robot_localization` according to their documentation is to only have one source of pose estimation, one source of twist estimation, and one source of orientation estimation. 

I will do more experimentation with the package before determining whether we need to gather another bag with another set of settings or even by reusing the older drivers.
