### ISSUE TITLE
Master Launch File

### ISSUE THREAD

**Issue by menson168** [SJSU-AD/FusionAD#206]
@drofp 
@joeyzhu00 
Please add to this discussion of what you would need to be included from your module in the master launch file for testing. Please note that we have a master launch file for data collection already. 

The new master launch file or any config will be placed under the ```common``` package.

**Comment by menson168** [comment]
Please follow this format in markdown.
```
${Name of module}
- ${Name of node}
    - ${Package in which the node belongs to}
```
EX:
High-level controller
- Control node 
    - Package: Control

OR

You may list your desired launch file to be included.
Please follow the format below.
```
  <include file="$(find {pkg_name})/launch/{launch_file_name}.launch" />
```
Simply replace the ```{pkg_name}``` with your package's name and the ```{launch_file_name}``` with the name of your launch file.

**Comment by joeyzhu00** [comment]
`robot_localization` and various support scripts which include `master_tf.cpp`, `odom_to_chassis_state.py`, `frame_calibration.cpp`, `odometry.cpp`, and Arduinos that read from the encoders.

- Package: `localization`

  - Launch File Name: `state_estimation.launch`

**Comment by menson168** [comment]
> `robot_localization` and various support scripts which include `master_tf.cpp`, `odom_to_chassis_state.py`, `frame_calibration.cpp`, `odometry.cpp`, and Arduinos that read from the encoders.
> 
> * Package: `localization`
>   
>   * Launch File Name: `state_estimation.launch`

Just reformatting it for the launch file format.
```
  <include file="$(find localization)/launch/state_estimation.launch" />
```

**Comment by menson168** [comment]
@drofp  Please put down your launch file for geodesy

**Comment by drofp** [comment]
Launch file for geodesy:
```
  <include file="$(find geodesy)/launch/geodesy.launch" />
```

**NOTE:** Geodesy may later be moved under the localization package as something like "Localization Utilities", per our brief discussion in person about a week ago.
