### ISSUE TITLE
[Control] Populate points to represent waypoint heading error range

### ISSUE THREAD

**Issue by joeyzhu00** [SJSU-AD/FusionAD#246]
Use more points to shade in the area of the waypoint donut in `rviz` to represent the waypoint heading error range

**Comment by menson168** [comment]
Do you mean the waypoints acceptance zone?

**Comment by drofp** [comment]
> Do you mean the waypoints acceptance zone?

Yes

**Comment by menson168** [comment]
> > Do you mean the waypoints acceptance zone?
> 
> Yes

Ok
