### ISSUE TITLE
Has maintenance stopped for this project? Do you have any plans to restart or update in the future

### ISSUE THREAD

**Issue by QSLee-Net** [SJSU-AD/FusionAD#259]
Has maintenance stopped for this project? Do you have any plans to restart or update in the future

**Comment by drofp** [comment]
Hi! Thanks for reaching out.

Maintenance has stopped for this project and there are no plans to restart or update in the future.

This project was a one year experiment and all contributors have moved on to other endeavors.

**Comment by QSLee-Net** [comment]
thanks
